---
title: "Practical 4: Scripts and Advanced Text Manipulation"
subtitle: "BIO511 Genomics - Scripting in bash"
author: "Tor Kling"
date: August 2026
format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false
    code-fold: false
    theme: minty
---

# Introduction

Now that you've learned the basics of the command-line, its high time that we start working on making our computational work structured and reproducible. While runnning pipes in our command line is a good way to execute many steps at once, writing our code in structured machine-readable text files called *scripts* allows us to expand the automate steps in a much more reproducible and capable way. In genomics, you'll pretty much always need to process massive datasets - think millions of sequences, GWAS data with millions of variants, or annotation files with complex formatting. Typically these files have a standardized structure, which the handling of we can automate by creating generalizable and well-formatted scripts.

::: {.callout-note}
## Learning Objectives
By the end of this practical you should be able to:

- Use `awk` to execute short programs for text manipulation
- Convert pseudocode into bash scripts
- Write iterative bash scripts using for loops and if/else statements
- Debug your scripts using global set-options, traps and custom error messages
- Be able to write basic flexible shell scripts using OPTARGS
:::

## Download data
For this practical, we will work with actual data. This means that the files will be much larger than before and you will really need to apply what you've learned. The data-package contains annotation data for 5 *E. coli* genomes. You may either retrieve these from the canvas course page, or if you want, you can try to fetch them from the HPC group directory (if you have access). 

```bash
# Download the data from canvas
# or 
# use scp (secure copy) to copy the data from the HPC group directory
scp <CIDusername>@vera2.c3se.chalmers.se:/cephyr/NOBACKUP/groups/n2bin_gu/practical4/DATAPRACTICAL4.tar.gz ~/CLI_intro/data/

# Unpack the data
# You might need to use a different command depending on your OS
# For Linux:
tar -xvzf ~/CLI_intro/data/DATAPRACTICAL4.tar.gz -C ~/CLI_intro/data/
```

---

# Text Manipulation with awk

## awk: Pattern Scanning and Processing Language

Throughout these first three practicals, you have become familar with pattern searching and input/output streams and redirection. `awk` is a powerful text processing toolset that builds on these concepts, allowing for programming like operations on files and pipe input with great flexibility. While it is a full programming language, we will introduce it mostly as a tool to use when it cant be accomplished with simpler commands like `grep`, `sed`, `cut`, `sort`, and `uniq`. Additionally, for a lot of cases it is easier to just use a modern interpreted programming language like Python or R, but when `awk` is the most suitable it can do said job very well. 

  - `awk` (Aho, Weinberger, and Kernighan): Allows for advanced text processing and file manipulation

::: {.callout-tip collapse="true"}
### Would you like to know more?
Awk programs can get quite complex, and we will not cover all its features here. However, it is a very useful tool to have in your toolbox, and I encourage you to explore it further on your own. A good resource is the [GNU Awk User's Guide](https://www.gnu.org/software/gawk/manual/gawk.html).
:::

Some key segments of an `awk`statement::

  - `-F`: Specifies the input delimiter (default is whitespace)
  - `BEGIN{}`: Block of programming that runs before processing any input lines (before any text is processed)
  - `END{}`: Block that runs after processing all input lines (after all text has been processed)
  - `{}`: Block that runs for each input line (the middle block, where the main processing happens)
  - `$1, $2, ...`: Represents the first, second, etc. fields (eg. columns) in the current line
  - `OFS`: Output delimiter (default is a space, can be set in BEGIN block)

What follows here are some examples of using awk. First off awk is great for quick column selection and simple filtering:
```bash
# Print seqid and type columns of a gff file
awk -F'\t' 'BEGIN{OFS="\t"} {print $1,$3,$9}' AF316.gff > seqid_type.tsv
# This was something we also could do with cut right?
cut -f1,3,9 AF316.gff > seqid_type_cut.tsv
```

You can also filter rows based on conditions, to retain only specific features 
```bash
#Here we can filter for only CDS features
awk -F'\t' '$3=="CDS"' AF316.gff > cds_features.tsv
# We can do something similar in grep here as well
grep "CDS" AF316.gff > cds_features_grep.tsv
```

Another thing is performing operations on the data in transit
```bash
# Here we can calculate the length of each CDS feature and output it as a new column
awk -F'\t' 'BEGIN{OFS="\t"} $3=="CDS"{print $1,$4,$5,$9,($5-$4+1)}' AF316.gff > cds_features_length.tsv

# Lets operate some more on the feature length file
# Calculate the total number of CDS features and their average length
awk -F'\t' 'BEGIN{OFS="\t"} {total_length+=($5-$4+1); count++} END{print "Total_CDS",count,"Average_Length",total_length/count}' cds_features_length.tsv
```
Here is where doing something equivalent in bash would need far more steps, likely iteratiing 
over the file line by line and performing calculations in a loop. This is where `awk` shines, as it allows for concise and efficient processing of structured text data without the need for command flows that should be a script in the first place. 
If you find any good awk one liners, its a good idea to keep them around for quick lookups of output data when youre running 
bioinformatic pipelines.

::: {.callout-important}
### Exercise: Using awk
Write an `awk` command to extract the `seqid`, `start`, and `end` columns from the `AF316.gff` file, but only for features of type `CDS`. Save the output to a new file called `genes.tsv`.

::: {.callout-tip collapse="true"}
### Solution:
So the solution was sort of already given in the instructions, good job if you got it right! 

```bash
awk -F'\t' 'BEGIN{OFS="\t"} $3=="CDS"{print $1,$4,$5}' AF316.gff > genes.tsv

# Head should look something like this:
head genes.tsv
# contig_1	92	691
# contig_1	841	1539
# contig_1	1539	1868
# contig_1	1865	4426
# contig_1	4419	4853
# contig_1	4835	5257
# contig_1	5273	6013
# contig_1	6021	6416
# contig_1	6413	6991
# contig_1	7003	7356
```
:::
:::

---

# Scripting 101 (in bash)

Now that we have learned a few more command-line tools, we can start writing our own scripts. A script is simply a text file containing a series of commands that can be executed in sequence. Scripts are useful for automating repetitive tasks, and for creating reproducible workflows.

For this practical, we will write a script that processes the AF genome files and looks for genes of a certain type

## Starting a bash script
We are already familiar with bash, one of the most common shell used in Linux and macOS, and is the default shell on most HPC systems. A bash script is simply a text file containing a series of bash commands that can be executed in sequence, and is interpreted by the bash interpreter. The first line of a bash script is typically a shebang line, which tells the system which interpreter to use to execute the script. The shebang line for a bash script is `#!/usr/bin/env bash`.

```bash
# Start by creating a new file called process_AF_genome.sh
touch process_AF_genome.sh

# Open the file in your editor and add the shebang line at the top
#!/usr/bin/env bash

# Now change the file permissions to make it executable
chmod +x process_AF_genome.sh

# To run the script, simply run the filename in your terminal
./process_AF_genome.sh
```

# Variables, for loops and if/else statements

For scripts to be automated, reusable and flexible we need three core concepts: **variables**, **for loops** and **if/else statements**. These are core to many programming languages, and are essential for writing scripts that can handle different inputs and conditions.

| Variables | For loops | If/else statements |
| --- | --- | --- |
| Variables are used to store values that can be used later in the script. | For loops are used to iterate over a list of items and execute a block of code for each item in the list. | If/else statements are used to execute a block of code if a certain condition is met, and another block of code if the condition is not met. |
| `GENE_NAME_PATTERN="gene_name"` | `for ffn_file in ${INPUT_DIR}/*.ffn; do ... done` | `if [ "${gene_count}" -gt 0 ]; then ... else ... fi` |


# Adding functionality to our script

## Variables

Lets begin by adding some variables to our script, we will use these variables to store the input and output file names, as well as the gene name pattern we want to look for in our ffn files. We will also initialize a variable to store the total number of genes matching the pattern found across all files.

```bash
# For these variables, we typically use the full path to the file, this makes it easier to run the script from any directory
# Swap the paths below with the correct paths to your files
INPUT_DIR="path/to/data"
OUTPUT_DIR="path/to/output"

# You can also use variables to store parameters, such as the gene name pattern we want to look for in our ffn files
GENE_NAME_PATTERN="gene_name"

# You can also Initialize variables to store intermediate values, such as the total number of genes matching the pattern found
TOTAL_GENES_FOR_PATTERN=0

```

## For loops

Since the ffn files we have contain a multitude of gene sequences and their headers, extracting these genes across multiple files will require repeated parsing setups. This is where **for loops** come in, they allow us to iterate over a list of items and execute a block of code for each item in the list. In our case, we can use a for loop to iterate over a list of input files and process each file in turn.

- `for`: A control flow statement that allows us to iterate over a list of items and execute a block of code for each item
- `do` and `done`: Keywords used to define the start and end of a loop block
- `basename`: A command that extracts the base name of a file (the file name without the path and extension), very useful for creating output file names based on input file names

```bash
# Initiate the gene_counts.tsv file with a header
[..1..] > ${OUTPUT_DIR}/gene_counts.tsv

# In our INPUT_DIR we have multiple ffn files, a good way (if you have a good structured folder) to iterate over all ffn files is to use a for loop with a wildcard
for ffn_file in ${INPUT_DIR}/*.ffn; do 

  base_name=$(basename ${ffn_file} .ffn)
  
  grep -A 1 -E "^>${GENE_NAME_PATTERN}" "${ffn_file}" > "${OUTPUT_DIR}/${base_name}_filtered.ffn"

  gene_count=$([..2..] || true)
  TOTAL_GENES_FOR_PATTERN=$((TOTAL_GENES_FOR_PATTERN + gene_count))

  echo -e "${base_name}\t${gene_count}" >> ${OUTPUT_DIR}/gene_counts.tsv

  echo "Processed ${ffn_file}, found ${gene_count} genes matching pattern '${GENE_NAME_PATTERN}'"
done

```

::: {.callout-important}
### Exercise: Missing code 
There are some missing pieces in the code above, indicated by [..N..]. They are single command replacements, and should be filled in with the correct command to make the script work as intended.

  1. The first missing piece is the command to create the `gene_counts.tsv` file with a header. This should be a command that creates a new file and writes the header line to it. The header line should be "File\tGene_Count" and needs to be printed to the file `${OUTPUT_DIR}/gene_counts.tsv`.
  2. The second missing piece is the command to count the number of genes found in the filtered ffn file. This should be a command that counts the number of lines in the file `${OUTPUT_DIR}/${base_name}_filtered.ffn` that start with `>`, which indicates a gene header line. The result should be stored in the variable `gene_count`.


:::{.callout-tip collapse="true"}
### Solution:
```bash

# 1
# Create the gene_counts.tsv file with a header
echo -e "File\tGene_Count" > ${OUTPUT_DIR}/gene_counts.tsv

# 2
# Count the number of genes found and add it to the total
grep -c '^>' "${OUTPUT_DIR}/${base_name}_filtered.ffn

```
:::
:::

# Improving your scripts: Adding debugging and flexibility

Bash scripts differ a bit from some other languages you might have tried befoer (eg. R, python), in that they without configuration will continue running even if an error occurs. Finding and catching these errors is the other half of programming, we will now introduce a few tools that can help you debug your bash scripts.

## Global set-options for debugging

Lets begin by setting the global options for our script, these are commands that define the general behaviour of our script. They will most likely always be in your scripts, and are a good starting point for debugging. A classic is the `set -euo` combination:

  - `set -e`: Exit immediately if a command exits with a non-zero status (i.e. as not expected)
  - `set -u`: Treat unset variables as an error when substituting (kills if you try to use a variable that has not been given a value)
  - `set -o pipefail`: Return the exit status of the last command in the pipe (if a command in a pipe fails, the whole pipe fails)

```bash
set -e  
set -u  
set -o pipefail  

# One additional setting is to add debugging output
# This will print each command before it is executed, which can be useful for debugging
# But it can also be very verbose, and clog up your output/logs
set -x  
```

## Custom error messages: Utilizing if/else statements for debugging
However, they wont help with finding the exact spot where the error occurs. One way to debug your code easily, is to use echo and create custom error messages at different stages of your script. Another way is to use traps, however we will not cover that here.

  - `if`: A control flow statement that allows us to execute a block of code if a certain condition is met
  - `then`: A keyword used to define the start of an if block
  - `else`: A keyword used to define an alternative block of code if the condition is not met
  - `fi`: A keyword used to define the end of an if block

```bash
# Here is an example of a custom error message
if [ ! -f "$INPUT_FILE" ]; then
  echo "Error: Input file $INPUT_FILE does not exist."
  exit 1
fi
```

The placement of error messages also need to make sense, for example if you are checking for the existence of a file, it should be placed before you try to read the file. If you are checking for the number of genes found in a file, it should be placed after you have processed the file. 

```bash
# The previous example makes sense to place after we assign the variable INPUT_FILE, but before we try to read the file.
# ex.
INPUT_FILE="${INPUT_DIR}/some_file.ffn"

if [ ! -f "$INPUT_FILE" ]; then
  echo "Error: Input file $INPUT_FILE does not exist."
  exit 1
fi
```

If we placed the conditional block before we defined INPUT_FILE, it would not make sense, as the script would fail every time. Same thing would happen if we placed it after we tried to read the file, as the script would have already failed before reaching the conditional block if the file did not exist. 

::: {.callout-important}
### Exercise: Custom error messages
Add custom error messages to your script to check for the following conditions:

1. Check if the input and output directories exist
2. Check if a name pattern is provided
3. Print the basename of the file being processed in the for loop
4. Check if any genes names matching the pattern were found in the current file

::: {.callout-tip collapse="true"}
### Solution:
Below are some suggestions for the custom error messages:
```bash
if [ ! -d "$INPUT_DIR" ]; then
  echo "Error: Input directory $INPUT_DIR does not exist."
  exit 1
fi
# and 
if [ ! -d "$OUTPUT_DIR" ]; then
  echo "Error: Output directory $OUTPUT_DIR does not exist."
  exit 1
fi

echo "Processing file: ${base_name}"

if [ "${gene_count}" -eq 0 ]; then
  echo "Warning: No genes matching pattern '${GENE_NAME_PATTERN}' found in ${ffn_file}"
fi
```
:::
:::

---

::: {.callout-tip collapse="true"}
## OPTARGS - Adding flags to make your scripts flexible (THIS IS OPTIONAL)
Up until now, our scripts have been quite rigid - they expect specific input files and parameters; an occasionally bad habit that people refer to as "hardcoding". However, in many scenarios, we often want our scripts to be more flexible and adaptable to different inputs and options. This is where OPTARGS comes in - a built-in bash tool that allows us to easily handle command-line options and arguments. You might recognize this from the command-line tools we've used so far, where we can add flags like `-h` for help or `-v` for verbose output. By using OPTARGS in our scripts, we can create flags for our own programs, making them more user-friendly and versatile.

A few key commands that we will use in this section:

- `getopts`: A built-in bash tool for parsing command-line options and arguments
- `case` statement: A control flow statement that allows us to execute different blocks of code based on the value of a variable

**Exercises**
```bash
# To begin using OPTARGS, we need to add a while loop at the top of our script to handle the options
# the OPTARG variable will hold the value of whatever comes after the flag in the command line
# A while loop iterates over the options provided to the script, and sets option variables based with the read value from the command line
while getopts "i:o:p:h" opt; do
  case $opt in
    i) INPUT_DIR="$OPTARG" ;;  # -i flag for input directory
    o) OUTPUT_DIR="$OPTARG" ;; # -o flag for output directory
    p) GENE_NAME_PATTERN="$OPTARG" ;; # -p flag for gene name pattern
    h) echo "Usage: $0 -i input_dir -o output_dir -p gene_name_pattern"  # -h flag for help
       exit 0 ;;
    *) echo "Invalid option: -$OPTARG" >&2
       exit 1 ;;
  esac
done

# We can add checks to ensure that the required options are provided
if [ -z "$INPUT_DIR" ] || [ -z "$OUTPUT_DIR" ]; then
  echo "Error: Input and output directories are required."
  echo "Usage: $0 -i input_dir -o output_dir -p gene_name_pattern"
  exit 1
fi

# Its also a good idea to set default values for optional parameters, you do this in the same way as when you set variables normally
GENE_NAME_PATTERN="${GENE_NAME_PATTERN:-gene_name}"  # Default pattern if not provided
# This sets GENE_NAME_PATTERN to the value provided by the -p flag, or to "gene_name" if no value is provided (as we did before)
```

**Now take the script you wrote before, and modify it to use OPTARGS for input and output files as well as a pattern selection**
**OPTARGS should be placed at the top of your script, after the shebang line and global settings**
**Remember to test your script with different combinations of options and arguments to ensure it behaves as expected**
:::

---

::: {.callout-important}
### Exercise: Using your script to biological questions
Now that you have a finished script, try to use it to answer the following questions:

1. How many genes in total across all three ffn files match the pattern "hypothetical protein"?

::: {.callout-tip collapse="true"}
### Answer:
```text
AF316: 
```
:::
:::

::: {.callout-important}
### Exercise: Describing your script in pseudocode
Now that you have a finished script, try to translate it into pseudocode. Once you have written a complete pseudocode, trade with a partner and see if they can understand what your script does based on your pseudocode. 
:::

---

::: {.callout-note}
## Key Takeaways
- `awk` is a powerful tool for advanced text processing and file manipulation, it can fulfill some roles without needing to write a full script.
- Writing scripts allows for structured, reproducible, and automated workflows
- Variables allow for storing values that can be used multiple times in a script, making it easier to modify and maintain
- For loops allow for iterating over a list of items and executing a block of code for each item, useful for processing multiple files
- If/else statements allow for conditional logic in scripts, enabling different actions based on input data or parameters
- Debugging is an essential skill for any programmer - use global settings, traps and custom error messages to help you find and fix errors in your code
- Using OPTARGS allows you to create flexible scripts that can handle different inputs and options. It also enables other people to use your scripts more easily
:::

::: {.callout-tip}
## Pro Tips for Scripting
- Test your awk commands on the first few lines with `head -5 data.csv | awk ...` before running on huge files!
- Use meaningful variable names (`RAW_SEQUENCES` not `rs`)
- Comment your scripts - Others cant read your mind!
- Test scripts on small datasets first
:::

---
