---
title: "Practical 0: Introduction"
subtitle: "BIO511 Genomics - Python Introduction and Setup"
author: "Alvar Almstedt, Emma Västerviga"
date: August 2026
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: false
    code-fold: false
    theme: cosmo
---

# Introduction to Python
Welcome!!

The exercises for this first lesson are meant to connect the python part of the course to what you have previously done in the unix shell scripting part of the course and are meant to be done in the terminal (not jupyter). You can start using jupyter after today.

If you think there is a lot of new syntax, don't worry. We will begin explaining the python syntax from the ground up starting tomorrow.

## Some useful links
[Jupyter notebooks (text)](https://www.datacamp.com/tutorial/tutorial-jupyter-notebook)

[Python in VS Code](https://code.visualstudio.com/docs/languages/python)

We are going to use github repos to present and compare assignments between groups. 
One of the members of each group will create the repo and add the other members of the group as collaborators.
Being able to work collaboratively on a github repo is among the leaning objectives of this part of the course.

# Exercises

## 1. Setup the github repo

1. Have one group member Create a github repo for this course. Name it `BIO511_python_2026_Group<X>`. 
  a.  Make sure it is public and add a README.md file.
2. Add the other group members as collaborators to the repo.
3. Each member of the group should clone the repo to their local machine.
4. After cloning, make a directory `members` and each member should create a file called 
`member_<name>.txt` in the `members` directory. Push the file to the repo. 
If you pull after everyone is done, you should be able to see the other members' files in the repo.
5. Add the url to your repo to your group's Canvas page.

## 2. Our first python script

Let’s start exploring Python! Some of the terms and tools used below we will go through 
in greater detail later on in the course. For now, let’s just try them out. 

To print any string, in this case hello, you can use the following line of code in python:
```python
print("hello!")
```
- Create a script first_python_script.py in a directory `practical_0`. 
Add a print command like the one above to print any string of text.
- Save the file and find it in the terminal.
- Run your script using the following command in bash: 
```python
python my_python_script.py
```
Any line starting with a hash `#` will be interpreted as a comment by python. A reasonable comment to the print command above could look something like this: `# Print "Hello"`. 
- Try adding a comment to your script as well.
- Instead of printing the string "hello", save a string of your choice to a variable and print that variable instead.

Tips:
- You can check your python version by typing `python -V` in the terminal. 
- Another useful argument is `-h`, which allows you to see what available options there are. Try it out by typing `python -h` in your terminal. 
- Throughout the course it will be nice to keep your code saved in scripts. 
By organizing them in directories for each practical, you will be able to easily find them later on.


## 3. Collaborating on a python script

- Try to add the script you just created to your github repo.
- See if each member can add their lines of code (i.e. initializing a variable and printing it) to the same script.
- Resolve any conflicts that may arise and make sure the script runs correctly after everyone has added their code.

Tips:
- It is a good idea to pull the repo before you start working on it, to make sure you have the latest version of the code.
- If issues arise when pulling the repo due to conflicts, you can try to stash your changes 
`git stash`, pull the repo and then apply your stashed changes `git stash pop`. 
- If you are not able to resolve the conflicts, you can always ask for help from your group members or the teachers.


::: {.callout-note}
## Learning Objectives So Far

- Create a GitHub repository and add collaborators
- Collaborate on a GitHub repository by cloning, adding files, and pushing changes
- Create a Python script and run it from the terminal
- Resolve conflicts when collaborating on a GitHub repository
:::

# Bash commands

You already had an introduction to bash. Did you know you can run bash commands in python as well? 

Open a python session by typing `python` in your terminal. To exit python, you’ll just have to type `quit()`. 

Let’s open python and try out some commands. A typical python module that you can use to perform the following commands is called `os`. First we have to import it in the python session to allow us to use the various tools provided by `os`. Start by opening a python session. Then, try out the following commands:
```python
import os
```
In bash we would write pwd to print the current working directory. In python it's:
```python
os.getcwd()
```
Create a new directory in the one you're in right now
```python
os.mkdir("test_dir_from_python")
```
Create a subdirectory in the one you just created
```python
os.mkdir("test_dir_from_python/subdir1")
```
You can create a new directory with a subdirectory in one line of code should you use the function makedirs() instead
```python
os.makedirs("test_dir_from_python/subdir2/subdir2.1")
```
What happens if you try to create the directories you just made again? Try it out.


Should you want to create a directory that might already exist without getting an error message, just to create it if it doesn't exist and otherwise do nothing, you can use the command `os.makedirs()` with an input argument especially made for cases like these, called `exist_ok`. `exist_ok` is set to `False` by default so we need to set it to `True` like this:
```python
os.makedirs("test_dir_from_python/subdir2/", exist_ok=True)
```
To list the contents of a directory, use `os.listdir()`. To have a look inside the directory we just made, run:
```python
os.listdir("test_dir_from_python")
```
Try to list the contents of the subdirectories `subdir1` and `subdir2` as well.

## basename

When coding we often work with file paths. However, we want to avoid hardcoding any path. Usually, we write scripts where we allow the user to set any path they want. Let’s say we’re working on a script where the user can specify their own input file path.

Start by moving the file `my_python_script.py` to one of the subdirectories you created, by using `os.rename()`:
```python
os.rename("/path/to/my_python_script.py", "test_dir_from_python/subdir1/my_python_script.py")
```
We can use a function called `basename` to work with any path we’re given. The `basename` function comes from a submodule within `os` called `path`. You can get only the file name from an entire path like this:
```python
# Save the path to a variable called my_file_path
my_file_path = 'test_dir_from_python/subdir2/my_python_script.py'
# Get only the file name
os.path.basename(my_file_path)
```

## arguments

But how can we allow any user of a script to specify their own path? We allow them to specify it when running the script from the terminal, to avoid them going in and messing with the actual script.

Now we are going to import a module called `sys`. Then, we will use a function from `sys` called `argv` to allow us to work with the command line argument that the user will give. Open up a new python script named `input_arguments_test.py`, preferably in `test_dir_from_python/subdir2/`, to allow us to work in the same directories. Write the following code in your file:
```python
import sys
# use the first and only argument from the user and save it as "input_string"
input_string = sys.argv[1]

# print the input argument
print(input_string)
```
Save the file and try to run it from the terminal. This time we should give an input argument, something it could print. Run it like this:
```python
python test_dir_from_python/subdir2/input_arguments_test.py "This is a test string"
```
Finally, we will combine what we’ve gone through so far. Create a script with an input argument that is a path to one of your files. Make the script print the basename of the file.


